routes/web.php
<?php

use App\Http\Controllers\BrandController;
use App\Http\Controllers\CarController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\RequestController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\BrandController as AdminBrandController;
use App\Http\Controllers\Admin\CategoryController as AdminCategoryController;
use App\Http\Controllers\Admin\CarController as AdminCarController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [CarController::class, 'index']);


Route::resource('cars', CarController::class)->only('index', 'show');
Route::resource('requests', RequestController::class)->only('store');


Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Car.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Car extends Model
{
    use HasFactory;

    protected $fillable = ['name', 'picture', 'description', 'brand_id', 'category_id'];

    /**
     * @return BelongsTo
     */
    public function category(): BelongsTo
    {
        return $this->belongsTo(Category::class);
    }

    /**
     * @return BelongsTo
     */
    public function brand(): BelongsTo
    {
        return $this->belongsTo(Brand::class);
    }

    /**
     * @return HasMany
     */
    public function requests(): HasMany
    {
        return $this->hasMany(Request::class);
    }
}

app/Http/Controllers/Admin/CarController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\CarRequest;
use App\Models\Brand;
use App\Models\Car;
use App\Models\Category;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class CarController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Application|Factory|View
     */
    public function index()
    {
        $cars = Car::all();
        return view('admin.cars.index', compact('cars'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Application|Factory|View
     */
    public function create()
    {
        $brands = Brand::all();
        $categories = Category::all();
        return view('admin.cars.create', compact('brands', 'categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param CarRequest $request
     * @return RedirectResponse
     */
    public function store(CarRequest $request)
    {
        $data = $request->all();
        $file = $request->file('picture');
        if (!is_null($file)) {
            $path = $file->store('pictures', 'public');
            $data['picture'] = $path;
        }
        $car = new Car($data);
        $car->save();
        return redirect()->route('admin.cars.index');
    }

    /**
     * Display the specified resource.
     *
     * @param Car $car
     * @return Application|Factory|View
     */
    public function show(Car $car)
    {
        return view('admin.cars.show', compact('car'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Car $car
     * @return Application|Factory|View
     */
    public function edit(Car $car)
    {
        $categories = Category::all();
        $brands = Brand::all();
        return view('admin.cars.edit', compact('categories', 'brands', 'car'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param CarRequest $request
     * @param Car $car
     * @return RedirectResponse
     */
    public function update(CarRequest $request, Car $car)
    {
        $data = $request->all();
        if($request->hasFile('picture')){
            $file = $request->file('picture');
            $path = $file->store('pictures', 'public');
            $data['picture'] = $path;
        }
        $car->update($data);
        return redirect()->action([self::class, 'index']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Car $car
     * @return RedirectResponse
     */
    public function destroy(Car $car)
    {
        $car->delete();
        return redirect()->action([self::class, 'index']);
    }
}

app/Http/Controllers/CarController.php
<?php

namespace App\Http\Controllers;

use App\Models\Car;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\Request;

class CarController extends Controller
{
    /**
     * @return Application|Factory|View
     */
    public function index()
    {
        $cars = Car::all();
        return view('client.cars.index', compact('cars'));
    }

    /**
     * @param Car $car
     * @return Application|Factory|View
     */
    public function show(Car $car)
    {
       return view('client.cars.show', compact('car'));
    }
}

resources/views/client/cars/show.blade.php
@extends('layouts.user')

@section('content')

    <div class="container">
        <div class="border-bottom pb-3 mb-3">
            <h3 class="pt-5 border-bottom pb-1 mb-3 ">Название модели: {{$car->name}}</h3>
            <div class="row row-cols-1 row-cols-md-2 row-cols-lg-2 .img-fluid. w-100%  h-auto ">
                <div class="col mb-4">
                    @if(!is_null($car->category))
                        <h4>Категория: {{$car->category->name}}</h4>
                    @endif
                    <br>
                    @if(!is_null($car->brand))
                        <h4>Бренд: {{$car->brand->name}}</h4>
                    @endif
                    <br>
                    <h4>Информация о модели:</h4>
                    @if (!is_null($car->description))
                        <p>{{$car->description}}</p>
                    @else
                        Нет описания
                    @endif
                </div>
                <div class="col mb-1 ">
                    <img src="{{asset('/storage/' . $car->picture)}}"
                         class="rounded mx-auto d-block img-fluid rounded float-right"
                         alt="{{asset('/storage/' . $car->picture)}}" width="400px" height="400px">
                </div>
            </div>
        </div>
        <a href="/" style="color: orange; font-size: large">На главную страницу</a>
        <br>
        <br>
        <br>
        <h2>Оставить заявку на данную модель</h2>
        <form action="{{route('requests.store')}}" method="post">
            @csrf
            <input type="hidden" value="{{$car->id}}" name="car_id">
            <div class="mb-3">
                <label for="name" class="form-label">Имя</label>
                <input type="text" class="form-control" id="name" name="name">
            </div>
            <div class="mb-3">
                <label for="phone" class="form-label">Телефон</label>
                <input type="text" class="form-control" id="phone" name="phone">
            </div>
            <button type="submit" class="btn btn-warning">Отправить</button>
        </form>
        <br>
        <br>
    </div>
@endsection