routes/web.php
<?php

use App\Http\Controllers\BrandController;
use App\Http\Controllers\CarController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\RequestController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\BrandController as AdminBrandController;
use App\Http\Controllers\Admin\CategoryController as AdminCategoryController;
use App\Http\Controllers\Admin\CarController as AdminCarController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [CarController::class, 'index']);


Route::resource('cars', CarController::class)->only('index', 'show');
Route::resource('requests', RequestController::class)->only('store');


Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Car.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Car extends Model
{
    use HasFactory;

    protected $fillable = ['name', 'picture', 'description', 'brand_id', 'category_id'];

    /**
     * @return BelongsTo
     */
    public function category(): BelongsTo
    {
        return $this->belongsTo(Category::class);
    }

    /**
     * @return BelongsTo
     */
    public function brand(): BelongsTo
    {
        return $this->belongsTo(Brand::class);
    }

    /**
     * @return HasMany
     */
    public function requests(): HasMany
    {
        return $this->hasMany(Request::class);
    }
}

app/Http/Controllers/Admin/CarController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\CarRequest;
use App\Models\Brand;
use App\Models\Car;
use App\Models\Category;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class CarController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Application|Factory|View
     */
    public function index()
    {
        $cars = Car::all();
        return view('admin.cars.index', compact('cars'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Application|Factory|View
     */
    public function create()
    {
        $brands = Brand::all();
        $categories = Category::all();
        return view('admin.cars.create', compact('brands', 'categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param CarRequest $request
     * @return RedirectResponse
     */
    public function store(CarRequest $request)
    {
        $data = $request->all();
        $file = $request->file('picture');
        if (!is_null($file)) {
            $path = $file->store('pictures', 'public');
            $data['picture'] = $path;
        }
        $car = new Car($data);
        $car->save();
        return redirect()->route('admin.cars.index');
    }

    /**
     * Display the specified resource.
     *
     * @param Car $car
     * @return Application|Factory|View
     */
    public function show(Car $car)
    {
        return view('admin.cars.show', compact('car'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Car $car
     * @return Application|Factory|View
     */
    public function edit(Car $car)
    {
        $categories = Category::all();
        $brands = Brand::all();
        return view('admin.cars.edit', compact('categories', 'brands', 'car'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param CarRequest $request
     * @param Car $car
     * @return RedirectResponse
     */
    public function update(CarRequest $request, Car $car)
    {
        $data = $request->all();
        if($request->hasFile('picture')){
            $file = $request->file('picture');
            $path = $file->store('pictures', 'public');
            $data['picture'] = $path;
        }
        $car->update($data);
        return redirect()->action([self::class, 'index']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Car $car
     * @return RedirectResponse
     */
    public function destroy(Car $car)
    {
        $car->delete();
        return redirect()->action([self::class, 'index']);
    }
}

app/Http/Controllers/CarController.php
<?php

namespace App\Http\Controllers;

use App\Models\Car;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\Request;

class CarController extends Controller
{
    /**
     * @return Application|Factory|View
     */
    public function index()
    {
        $cars = Car::all();
        return view('client.cars.index', compact('cars'));
    }

    /**
     * @param Car $car
     * @return Application|Factory|View
     */
    public function show(Car $car)
    {
       return view('client.cars.show', compact('car'));
    }
}

resources/views/admin/cars/create.blade.php
@extends('layouts.admin')

@section('content')
    <form action="{{route('admin.cars.store')}}" enctype="multipart/form-data" method="post">
        @csrf
        <div class="mb-3">
            <label for="name" class="form-label">Name</label>
            <input type="text" class="form-control" name="name" id="name">
        </div>
        <div class="mb-3">
            <label for="description">
                <textarea name="description" id="description" cols="30" rows="10"></textarea>
            </label>
        </div>
        <div class="mb-3">
            <label for="brand_id">Choose brand</label>
            <select class="custom-select" name="brand_id">
                @foreach($brands as $brand)
                    <option value="{{$brand->id}}">{{$brand->name}}</option>
                @endforeach
            </select>
        </div>
        <div class="mb-3">
            <label for="category_id">Choose category</label>
            <select class="custom-select" name="category_id">
                @foreach($categories as $category)
                    <option value="{{$category->id}}">{{$category->name}}</option>
                @endforeach
            </select>
        </div>
        <div class="mb-3">
            <label for="picture" class="form-label">Picture</label>
            <input type="file" class="form-control" name="picture" id="picture">
        </div>
        <button type="submit" class="btn btn-info">Create</button>
    </form>
@endsection

resources/views/admin/cars/edit.blade.php
@extends('layouts.admin')

@section('content')
    <form action="{{route('admin.cars.store', $car)}}" enctype="multipart/form-data" method="post">
        @csrf
        @method('put')
        <div class="mb-3">
            <label for="name" class="form-label">Name</label>
            <input type="text" class="form-control" name="name" id="name" value="{{$car->name}}">
        </div>
        <div class="mb-3">
            <label for="description">
                <textarea name="description" id="description" cols="30" rows="10">{{$car->description}}</textarea>
            </label>
        </div>
        <div class="mb-3">
            <label for="brand_id">Choose brand</label>
            <select class="custom-select" name="brand_id">
                @foreach($brands as $brand)
                    <option value="{{$brand->id}}">{{$brand->name}}</option>
                @endforeach
            </select>
        </div>
        <div class="mb-3">
            <label for="category_id">Choose category</label>
            <select class="custom-select" name="category_id">
                @foreach($categories as $category)
                    <option value="{{$category->id}}">{{$category->name}}</option>
                @endforeach
            </select>
        </div>
        @if($car->picture)
                <img src="{{asset('/storage/' . $car->picture)}}"
                     alt="{{asset('/storage/' . $car->picture)}}"
                     style="width: 150px; height: 150px">
        @endif
        <div class="mb-3">
            <label for="picture" class="form-label">Picture</label>
            <input type="file" class="form-control" name="picture" id="picture">
        </div>
        <button type="submit" class="btn btn-info">Create</button>
    </form>
@endsection

resources/views/admin/cars/index.blade.php
@extends('layouts.admin')

@section('content')

    <a href="{{route('admin.cars.create')}}" class="btn btn-primary">Create a new car</a>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">Name</th>
            <th scope="col">Picture</th>
            <th scope="col">Category</th>
            <th scope="col">Brand</th>
            <th scope="col">Description</th>
            <th scope="col">Actions</th>
        </tr>
        </thead>
        <tbody>
        @foreach($cars as $car)
        <tr>
            <td>{{$car->name}}</td>
            @if($car->picture)
                <td>
                    <img src="{{asset('/storage/' . $car->picture)}}"
                         alt="{{asset('/storage/' . $car->picture)}}"
                         style="width: 150px; height: 150px">
                </td>
            @endif
            @if(!empty($car->category->name))
            <td>{{$car->category->name}}</td>
            @else
                <td>---</td>
                @endif
            @if(!empty($car->brand->name))
                <td>{{$car->brand->name}}</td>
            @else
                <td>---</td>
            @endif
            <td>{{$car->description}}</td>
            <td>
                <div class="btn-group">
                    <form action="{{route('admin.cars.destroy', $car)}}" method="post">
                        @csrf
                        @method('delete')
                        <button type="submit" class="btn btn-outline-danger">Delete</button>
                    </form>
                    <a href="{{route('admin.cars.edit', $car)}}" class="btn btn-outline-dark">Edit</a>
                    <a href="{{route('admin.cars.show', $car)}}" class="btn btn-outline-info">Show</a>
                </div>
            </td>
        </tr>
        @endforeach
        </tbody>
    </table>

@endsection()

resources/views/admin/cars/show.blade.php
@extends('layouts.admin')

@section('content')
    <br>
    <br>
    <p>
        picture:    <img src="{{asset('/storage/' . $car->picture)}}" alt="{{asset('/storage/' . $car->picture)}}"
                         style="width: 300px; height: 300px">
    </p>
    <p>
        name:    {{$car->name}}
    </p>
    <p>
        description: {{$car->description}}
    </p>
    <p>
        brand: {{$car->brand->name}}
    </p>
    <p>
        category: {{$car->category->name}}
    </p>
    <a href="{{route('admin.categories.index')}}">Back</a>
@endsection